package de.pfiva.data.ingestion.service;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import com.fasterxml.jackson.databind.ObjectMapper;

import de.pfiva.data.ingestion.ConfigProperties;
import de.pfiva.data.ingestion.DataIngestionProperties;
import de.pfiva.data.ingestion.data.NLUDataIngestionDBService;
import de.pfiva.data.ingestion.model.IntentNames;
import de.pfiva.data.model.FeedbackType;
import de.pfiva.data.model.Tuple;
import de.pfiva.data.model.notification.FeedbackData;
import de.pfiva.data.model.snips.SnipsOutput;

@Service
public class FeedbackService {

	@Autowired RestTemplate restTemplate;
	@Autowired DataIngestionProperties properties;
	@Autowired ConfigProperties configProperties;
	@Autowired NLUDataIngestionDBService dbService;
	@Autowired ObjectMapper objectMapper;
	@Autowired FirebaseService firebaseService;
	
	private static Logger logger = LoggerFactory.getLogger(FeedbackService.class);
	
	public void sendFeedback(SnipsOutput snipsOutput, int queryId) {
		// 1. Generate Feedback
		// 2. Push feedback to db
		// 3. Send Feedback
		
		Tuple<FeedbackType, String> feeback = generateFeedbackQuery(snipsOutput);
		int feedbackId = pushFeedbackToDB(feeback, queryId);
		postFeedbackToFirebase(feeback, feedbackId);
	}
	
	private int pushFeedbackToDB(Tuple<FeedbackType, String> feeback, int queryId) {
		int feedbackId = 0;
		if(feeback != null) {
			feedbackId = dbService.pushFeedbackToDB(queryId, feeback.getY());
		}
		return feedbackId;
	}

	private Tuple<FeedbackType, String> generateFeedbackQuery(SnipsOutput snipsOutput) {
		// Feedback query can be generated by: 
		// 1. knowing the intent
		// 2. general feedback
		
		Tuple<FeedbackType, String> feedback = null;
		if(snipsOutput !=null) {
			String userQuery = snipsOutput.getInput();
			if(userQuery != null && !userQuery.trim().isEmpty()) {
				if(snipsOutput.getIntent() != null) {
					String feedbackQuery = "Did you ask about "
							+ parseIntentToUserReadableString(snipsOutput
									.getIntent().getIntentName())
							+ "?";
					feedback = new Tuple<FeedbackType, 
							String>(FeedbackType.INTENT_CLASSIFIED, feedbackQuery);
				} else {
					feedback = new Tuple<FeedbackType,
							String>(FeedbackType.GENERAL, 
									configProperties.getConfigValues().get("pfiva_default_feedback_query"));
				}
			}
			logger.info("Feedback generated of type [" + feedback.getX() + "],"
					+ " feedback query [" + feedback.getY() + "]");
		}
		return feedback;
	}
	
//	@Async
	private void postFeedbackToFirebase(Tuple<FeedbackType,
			String> feeback, int feedbackId) {
		
		FeedbackData data = new FeedbackData();
		data.setFeedbackId(feedbackId);
		data.setFeedbackType(feeback.getX());
		data.setText(feeback.getY());
		firebaseService.sendRequestToFirebaseServer(data, properties.getMobileClientName());
		
//		HttpHeaders headers = new HttpHeaders();
//		headers.setContentType(MediaType.APPLICATION_JSON);
//		String firebaseServerKey;
//		String clientName;
//		if(properties.getNotificationClient() == NotificationClient.MOBILE) {
//			firebaseServerKey = "key=" + properties.getMobileFirebaseServerKey();
//			clientName = properties.getMobileClientName();
//		} else {
//			firebaseServerKey = "key=" + properties.getWearFirebaseServerKey();
//			clientName = properties.getWearClientName();
//		}
//		headers.set(HttpHeaders.AUTHORIZATION, firebaseServerKey);
//		
//		RequestModel requestModel = new RequestModel();
//		FeedbackData data = new FeedbackData();
//		data.setFeedbackId(feedbackId);
//		data.setFeedbackType(feeback.getX());
//		data.setText(feeback.getY());
//		requestModel.setData(data);
//		requestModel.setTo(getClientToken(clientName));
//		
//		String requestBody = null;
//		try {
//			requestBody = objectMapper.writeValueAsString(requestModel);
//		} catch (JsonProcessingException e) {
//			logger.error("Error while forming request body for firebase");
//		}
//		logger.info("Request body for firebase [" + requestBody + "]");
//				
//		HttpEntity<?> requestEntity = new HttpEntity<Object>(requestBody, headers);
//		
//		ResponseEntity<String> response = restTemplate.exchange(properties.getFirebaseUrl(),
//				HttpMethod.POST, requestEntity, String.class);
//		logger.info("Response from firebase server [" + response.getBody() + "]");
//		
//		return CompletableFuture.completedFuture(response.getBody());
	}

	private String getClientToken(String clientName) {
		return dbService.getClientToken(clientName);
	}

	private String parseIntentToUserReadableString(String intentName) {
		String parsedIntent = null;
		if(intentName != null && !intentName.trim().isEmpty()) {
			switch (intentName) {
			case IntentNames.SEARCHWEATHERFORECAST:
				parsedIntent = "weather";
				break;
			case IntentNames.SEARCHWEATHERFORECASTCONDITION:
				parsedIntent = "weather forecast conditions";
				break;
			case IntentNames.SEARCHWEATHERFORECASTITEM:
				parsedIntent = "weather forecast conditions";
				break;
			case IntentNames.SEARCHWEATHERFORECASTTEMPERATURE:
				parsedIntent = "weather forecast conditions";
			default:
				parsedIntent = IntentNames.UNKNOWN_INTENT;
				break;
			}
		}
		return parsedIntent;
	}

}
