version: '3'

services:
  pfiva-mysql:
    image: mysql:8.0.12
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pfiva_db
    ports:
      - "3306:3306"
    volumes:
      - "./data:/var/lib/mysql:rw"
  
  pfiva-service:
    image: pfiva-data-ingestion:latest
    depends_on:
      - pfiva-mysql
    ports:
      - "9001:9001"
    environment:
      - DATABASE_HOST=pfiva-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=pfiva_db
      - DATABASE_PORT=3306
  
  pfiva-web:
    image: pfiva-angular-app
    depends_on:
      - pfiva-service
    ports:
      - "4200:4200"
  
  pfiva-nlu-service:
    image: snips-nlu-app:latest
    ports:
      - "5000:5000"