version: '2'

services:
  pfiva-mysql:
    image: mysql:8.0.12
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pfiva_db
    ports:
      - "3306:3306"
    volumes:
      - "/Users/rahullao/data:/var/lib/mysql:rw"
      - "./resources/init.sql:/docker-entrypoint-initdb.d/init.sql"
  
  pfiva-service:
    image: rahullao/pfiva-data-ingestion:latest
    depends_on:
      - pfiva-mysql
    links:
      - "pfiva-mysql:pfiva-mysql"
      - "pfiva-nlu-service:pfiva-nlu-service"
    ports:
      - "9001:9001"
    environment:
      - DATABASE_HOST=pfiva-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=pfiva_db
      - DATABASE_PORT=3306
  
  pfiva-web:
    image: rahullao/pfiva-angular-app
    depends_on:
      - pfiva-service
    links:
      - "pfiva-service:pfiva-service"
    ports:
      - "4200:4200"
  
  pfiva-nlu-service:
    image: rahullao/snips-nlu-app:latest
    ports:
      - "5000:5000"

#  pfiva-speech-service:
#    image: pfiva-speech-client:latest
#    ports:
#      - "9002:9002"